name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install dependencies
        run: yarn

      - name: Build everything
        run: yarn build

  style:
    name: Styling checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install dependencies
        run: yarn

      - name: Format code
        run: yarn format

      - name: Lint code
        run: yarn lint
