name: styling

on:
  push:
    branches:
      - main

jobs:
  style:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install dependencies
        run: yarn

      - name: Format code
        run: yarn format

      - name: Lint code
        run: yarn lint

      - name: Compile TS code
        run: yarn build
