name: test

on:
  push:
    branches:
      - main
      - erhant/tests

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install Circom
        run: |
          git clone https://github.com/iden3/circom.git
          cd circom
          cargo build --release
          cargo install --path circom

      - name: Print help
        run: circom --help
